# Generated by Django 2.2.6 on 2019-10-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191006_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketatest',
            name='Time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='anketatest',
            name='personal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='anketatest',
            name='physReady',
            field=models.IntegerField(null=True),
        ),
    ]
