# Generated by Django 2.2.6 on 2019-10-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191007_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='html',
            field=models.TextField(blank=True, max_length=10000, verbose_name='карта'),
        ),
    ]
